version: '3.8'

services:
  API:
    image: reservly
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/reservly_db
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=papimaciano
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=papimaciano
      - MYSQL_DATABASE=reservly_db
      - MYSQL_USER=root
      - MYSQL_PASSWORD=papimaciano