
#Jpa database connection
spring.datasource.url=jdbc:mysql://localhost:3306/reservly_db
spring.datasource.username=root
spring.datasource.password=papimaciano
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect

spring.mail.username=reservlylodging@gmail.com
spring.mail.password=jgobityfdqurychz